---
title: "discrete_distributions"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Discrete Distributions Summary
### Bernoulli 
```{r}
# Example 2.4-3
dbinom(1, 5, 0.2) / 5
```
```{r}
# Example 2.4-4
dbinom(3, 5, 0.8) / choose(5, 3)
# 0.02048
```
```{r}
# check with textbook
0.8^3 * 0.2^2
```
### Binomial
```{r}
# Example 2.4-5
dbinom(2, 8, 0.2)
```
```{r}
# use f(x) 
choose(8,2)*0.2^2 * 0.8^6
# 0.2936013
```

### Hypergeometric 
```{r}
# Example 2.5-2
dhyper(2, 10, 40, 7)
# 0.2964463
```
```{r}
# you can also use definition to find the probability
choose(10, 2) * choose(40, 5) / choose(50, 7)
```
### Negative Binomial
```{r}
# Example 2.6-2
choose(11, 9) * dnbinom(12, 10, 0.8) # not working
```
```{r}
# use formula
choose(11, 9) * 0.8^10 * 0.2^2
```

### Poisson 
```{r}
# Example 2.7-3
dpois(0, 4)
```
```{r}
ppois(4, 4)
```
```{r}
# example 2.7-4
1 - ppois(4, 6) # pay attention to reverse thinking !
```

* comparison between sample size and p
* based on Example 2.6-6
```{r}
x <- 0:25
plot(x, dpois(x, 2.5), type = 'h', ylim = c(0, 0.3))
points(x, dbinom(x, 25, 0.1), col = 'red')
```
```{r}
# to show the gap between binomial and poission is large for large p = 0.3
x <- 0:40
plot(x, dpois(x, 12), type = 'h', ylim = c(0, 0.2))
points(x, dbinom(x, 40, 0.3), col = 'red')
```

## Reference: Probability and Statistical Inference, 10th Edition