---
title: "EPI - buy and sell stocks once"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set up python environment in R
```{r include=FALSE}
library(reticulate)
use_condaenv("deeplearning")
py_config()
```

## Run python script
```{r}
source_python('buy_sell_stocks.py')
```
## Plot stocks trends
```{r}
stocks <- c(310, 310, 275, 275, 260, 260, 260, 430, 230, 230)
plot(stocks, type = "l", xlab = "days")
```

## Find max profit by selling
```{r}
max_profit <- buy_and_sell_stock_once(stocks)
max_profit
```

## Run python scripts in RStudio
```{python}
# buy and sell stocks
def buy_and_sell_stock_once2(prices):
	min_price_so_far , max_profit = float('inf'), 0.0
	for price in prices:
		max_profit_sell_today = price - min_price_so_far
		max_profit = max(max_profit, max_profit_sell_today)
		min_price_so_far = min(min_price_so_far, price)
	return max_profit
```
* Somehow, this passes the compliling, but does not produce function like source_python did.
* Ref: http://elementsofprogramminginterviews.com/sample/epilight_python_new.pdf


